.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd March 25, 2013
.Dt PKG-ADD 8
.Os
.Sh NAME
.Nm "pkg add"
.Nd Registers individual packages and installs them on the system
.Sh SYNOPSIS
.Nm
.Op Fl AfInqy
.Ar <pkg-name>
.Nm
.Op Fl AfInqy
.Ar <protocol>://<path>/<pkg-name>
.Sh DESCRIPTION
.Nm
installs each of the named packages from either a local or a remote
source, in the order given on the command line.
If a previous version of a package is already installed,
.Nm
will ask the user to confirm performing an upgrade.
Package installations will fail unless all necessary dependencies are
already installed, or unless the
.Fl f
flag is used.
.Nm
will attempt to install any missing dependencies by constructing a
path or URL using the dependency name and version and the same
directory or base URL as the named package.
Confirmation of any questions is assumed when the
.Fl y
flag is used, or the
.Cm ASSUME_ALWAYS_YES
configuration variable is set in
.Fa pkg.conf .
.Nm 
will refuse to reinstall a package at the same version as one
previously installed, or to downgrade a package, unless the
.Fl f
flag is given.
.Pp
When installing from a remote source you need to specify
the protocol to use when fetching the package.
Currently supported protocols are FTP, HTTP and HTTPS.
Downloaded packages are stored in
.Cm PKG_CACHEDIR .
There is no means of predicting if there is sufficient space
available to contain the downloads.
.Nm
will attempt to install as many of the requested packages or
dependencies as it has successfully been able to fetch.
.Pp
When installing from a local filesystem, you may use either
a
.Fa file://
URL, or use a simple filesystem path.
Using a
.Fa file://
URL will cause the package to be copied to
.Cm PKG_CACHEDIR .
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl f
Force reinstallation or downgrade when a previously installed version
of a package is not older than the package given as argument.
Force installation of a package even though all the packages it
depends on have not yet been installed.
Force installation of a package built for a non-matching architecture.
.It Fl I
If any installation scripts (pre-install or post-install) exist for a given
package, do not execute them.
.It Fl A
Mark the installed packages as orphan.
Will be automatically removed if no other packages depend on them.
For more information please refer to
.Xr pkg-autoremove 8
.It Fl n
Dry-run mode: show what would be done, but do not proceed with adding
any packages.
.It Fl q
Quiet mode: reduce the amount of informational messages printed while
.Nm
runs.
Setting
.Fl n
overrides the effect of
.Fl q .
.It Fl y
Assume a yes answer to all confirmatory questions.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev ASSUME_ALWAYS_YES
.It Ev HANDLE_RC_SCRIPTS
.It Ev PKG_DBDIR
.It Ev PKG_CACHEDIR
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg.conf 5 ,
.Xr pkg 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-convert 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
